# Generated by Django 6.0.3 on 2026-03-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
