# Generated by Django 6.0.4 on 2026-04-18 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='disponibilidad',
            new_name='disponiblidad',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imagen',
            new_name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pos.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pos.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='state_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='state_stock',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku', 'barcode'], name='pos_product_sku_50a5c5_idx'),
        ),
    ]
